model:
    arch: CSFINet
data:
    dataset: HVSMR
    train_split: train
    val_split: val
    test_split: test
    path:

training:
    gpu_idx: 0
    train_iters: 40000
    batch_size: 1
    val_interval: 200
    n_workers: 4
    print_interval: 100
    optimizer:
        name: 'adam'
        lr: 6.0e-4
        weight_decay: 0.0005

    loss:
        name: 'cross_entropy'
    lr_schedule: 
        name: 'constant_lr'
    resume:
    model_dir: './trained'

testing:
    trained_model: './trained/fin_without_dual.pkl'
    path: './tested'
    boxplot: False